### ISSUE TITLE
FR: ESP-IDF Custom Components

### ISSUE THREAD

**Issue by oliverjc** [platformio/platform-espressif32#202] opened 2019-07-17 12:23 UTC
I would love to have the ability to include custom ESP-IDF components, such as [ESP-DSP](https://github.com/espressif/esp-dsp), in my projects. 

In the meantime, If anybody could share their workflow of using VS code, ESP-IDF, and Arduino as a component together it would be greatly appreciated.

Similar Requests:
[[1]](https://github.com/platformio/platform-espressif32/issues/182), [[2]](https://community.platformio.org/t/adding-components-in-esp-idf/6764)

**Comment by valeros** [comment] 2019-09-18 14:51
Closing as duplicate of #182

**Closed by valeros** 2019-09-18 14:51 UTC
Labels: feature
