### ISSUE TITLE
I tried to use the latest Arduino kernel, but it doesn't seem to be supported. What can I do to use the latest Arduino kernel?

### ISSUE THREAD

**Issue by 0cococ** [platformio/platform-espressif32#1450] opened 2024-08-27 02:48 UTC
![image](https://github.com/user-attachments/assets/a4ab59a5-ab5c-4d3a-ace7-350a7762e656)
![image](https://github.com/user-attachments/assets/f6a76330-663b-4fbf-a1b9-23493ee83de7)
I tried to use the latest Arduino kernel, but it doesn't seem to be supported. What can I do to use the latest Arduino kernel?

**Comment by 0cococ** [comment] 2024-08-27 02:49
![image](https://github.com/user-attachments/assets/00b23485-eeb2-436d-a5fb-834790bbe862)

**Comment by 45gfg9** [comment] 2024-08-27 03:38
See #1225.

**Comment by valeros** [comment] 2024-08-27 09:10
Closed as duplicate of #1225.

**Closed by valeros** 2024-08-27 09:10 UTC
