### ISSUE TITLE
Board AtomLite 2020

### ISSUE THREAD

**Issue by AlbertoFeliy** [platformio/platform-espressif32#428] opened 2020-11-11 12:45 UTC
Hi my friends,

I want to make codes for the AtomLite2020 from M5Stack. But I cannot find the Atom in Boards. 

I have looked it up in Visual Basic - PIO Home - Boards 

Please add the M5Stack AtomLite2020 to the  boards,

thanks, 

Feliy

**Comment by barndawgie** [comment] 2023-12-18 17:38
Seems like this is a dupe of my issue: https://github.com/platformio/platform-espressif32/issues/1258

If so, seems like it can be closed and you can use `m5stack-atom`

**Comment by valeros** [comment] 2023-12-18 17:53
That's right, `m5stack-atom` can be used, just be careful with predefined pins like `LED_BUILTIN` as they may not match your hardware.

**Closed by valeros** 2023-12-18 17:53 UTC
Labels: board request
