### ISSUE TITLE
How to use tinyusb in the espidf project and turn on my I can't use it right now, I need to use tinyusb for hid

### ISSUE THREAD

**Issue by 0cococ** [platformio/platform-espressif32#1458] opened 2024-09-12 04:33 UTC
![image](https://github.com/user-attachments/assets/b11942de-ca3c-41c6-b13c-9d2e8c30d317)
![image](https://github.com/user-attachments/assets/51ab8f00-a8da-4f1a-b335-dbb0bead34f1)
How to use tinyusb in the espidf project and turn on my I can't use it right now, I need to use tinyusb for hid

**Comment by valeros** [comment] 2024-09-12 09:31
Duplicate of https://github.com/platformio/platform-espressif32/issues/1042

**Closed by valeros** 2024-09-12 09:31 UTC
