### ISSUE TITLE
[Feature] Add support for esf-idf project

### ISSUE THREAD

**Issue by fanthos** [platformio/platform-espressif32#44] opened 2017-09-11 17:37 UTC
I am trying to build https://github.com/MrBuddyCasino/ESP32_MP3_Decoder .
That project using component.mk, component folder in project and Kconfig, so that project is not able to build on PlatformIO without lots of modification.
I'm also checking examples from official esp32 repo, the source files are located on folder `main`.
Are there any plans to support esf-idf project directly or import?

Another problem is that PlatformIO does not have Kconfig support. After I run `make menuconfig` I got sdkconfig, I have to manually to convert it to sdkconfig.h if I want to build the project using PlatformIO. I hope there is easier way to do that.

**Comment by huming2207** [comment] 2017-09-15 11:18
Agree. But the problem is that ESP-IDF needs to configure with KBuild (the ```make menuconfig```) unless some extra workarounds are implemented. For example, Arduino-ESP32 used precompiled binaries from ESP-IDF.

**Comment by fanthos** [comment] 2017-09-15 11:19
The KBuild file can be processed by a library like https://github.com/ulfalizer/Kconfiglib , but still lots of work need to be done.

**Comment by Gouthamm4G** [comment] 2018-04-18 13:15
@fanthos @huming2207 But right now, just supporting the folder structure of the esp-idf project layout and configuring them separately in the terminal would still be a quick viable workaround. It wouldn't need much changes to the existing system. Just add a few extra targets to the `esp-idf.py` file within the platform folder as per your requirements and you are good to go.

**Comment by ivankravets** [comment] 2018-05-25 12:38
Duplicate of https://github.com/platformio/platform-espressif32/issues/20

**Closed by ivankravets** 2018-05-25 12:38 UTC
Labels: enhancement
