### ISSUE TITLE
Stuck in `Installing windows-curses package` and fail

### ISSUE THREAD

**Issue by LUCKandII** [platformio/platform-espressif32#1214] opened 2023-10-20 01:15 UTC
## Environment
* PlatformIO Core, version 6.1.11
* Windows11 22H2
* VsCode PlatformIO IDE extension setting:
```js
    "platformio-ide.useBuiltinPIOCore": false,
    "platformio-ide.customPATH": "C:/Users/lucka/.platformio/penv/Scripts",
    "platformio-ide.useBuiltinPython": false,
```
* System Python version:3.12.0,installed for all user.
* Project under tested:[platform-espressif32/examples/espidf-arduino-blink/](https://github.com/platformio/platform-espressif32/tree/516520f851f843ad79131ee5eb3affb7555cf587/examples/espidf-arduino-blink)

## Description
* When building a project, uploading a firmware, always meet this `Installing windows-curses package` fail error. Building and uploading finally done but I always had to wait extra 1minute or more when it stucked. See the screenshots below.
* [Windows-curses](https://github.com/zephyrproject-rtos/windows-curses) dosen't support python 3.12.0 indeed yet.
* When running menuconfig, also meet this `Installing windows-curses package` fail error. See details in https://github.com/platformio/platform-espressif32/issues/1213

I really need help, whether it's a permanent or temporary solution🥲

![image](https://github.com/platformio/platform-espressif32/assets/44010936/bbae7fa1-bded-4e08-ad4d-68966e32f57c)
![image](https://github.com/platformio/platform-espressif32/assets/44010936/d7a1629d-bf8e-4957-9fe1-b0fba8f5e091)

**Comment by valeros** [comment] 2023-10-23 10:44
Closing as duplicate of #1213.

**Closed by valeros** 2023-10-23 10:44 UTC
